#!/bin/bash

cd /home/omk/Insync/otaviokavakama@gmail.com/Google\ Drive/WEBSITE/kavotaman.github.io

sleep 1

./update_cv_pdf

# sed -i '14,$d' cv_pdf/cv_pdf.md

# sed -n '26,$p' cv.md > cv_temp

# sed -i '/Back to the top/d' cv_temp

# line=13

# sed -i -e "${line}r cv_temp" cv_pdf.md

sleep 1

TODAY1=$(date +%F)

wkhtmltopdf -s letter -B 4 -L 4 -R 4 -T 4 --footer-font-size 10 --footer-left 'Otavio Manzano Kavakama - cellist' --footer-right [page]/[topage] --footer-line http://127.0.0.1:4000/cv_pdf/ /home/omk/Insync/otaviokavakama@gmail.com/Google\ Drive/CV\ RESUME/Otavio_Manzano_Kavakama_CV_$TODAY1.pdf

# wkhtmltopdf -s letter --footer-font-size 10 --footer-left 'Otavio Manzano Kavakama - cellist' --footer-right [page]/[topage] --footer-line https://otaviomk.com/cv_pdf/ /home/omk/Insync/otaviokavakama@gmail.com/Google\ Drive/DMA\ BGSU\ 2019-/PORTFOLIO/Otavio_Manzano_Kavakama_CV_$TODAY1.pdf
