#!/bin/bash
pkill -f -31 nwg-wrapper

while pgrep -u $UID -x nwg-wrapper >/dev/null; do sleep 1; done

nwg-wrapper -s wttr.sh -r 300000 -c wttr.css -p left -ml 20 -mt 20 -sq 31 -a start &

nwg-wrapper -s timezones.sh -r 1000 -c timezones.css -p right -mr 50 -a start -mt 50 -j right -sq 31 & exit

