[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 11

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.8

[window.padding]
x = 9
y = 3
